// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHFp0wXIPZHT5FhsYZglU7-1MMav2tEQA',
    appId: '1:132264684965:web:9e6a134cd0aebfe7610c4c',
    messagingSenderId: '132264684965',
    projectId: 'flash-chat-c716f',
    authDomain: 'flash-chat-c716f.firebaseapp.com',
    storageBucket: 'flash-chat-c716f.appspot.com',
    measurementId: 'G-30QJ9JT9DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn_Hteah-5_gsxirpHeI1V9-aMJgU9ios',
    appId: '1:132264684965:android:a76e9769da540f52610c4c',
    messagingSenderId: '132264684965',
    projectId: 'flash-chat-c716f',
    storageBucket: 'flash-chat-c716f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXn6HHCSJseMGg5d5BV2-t6illOg3ZT8Y',
    appId: '1:132264684965:ios:9fc96c5762c47eb5610c4c',
    messagingSenderId: '132264684965',
    projectId: 'flash-chat-c716f',
    storageBucket: 'flash-chat-c716f.appspot.com',
    iosClientId: '132264684965-s7vete8inecoa6ccsb9i820ip6l5d988.apps.googleusercontent.com',
    iosBundleId: 'com.flashchat.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXn6HHCSJseMGg5d5BV2-t6illOg3ZT8Y',
    appId: '1:132264684965:ios:878106d267ce3a01610c4c',
    messagingSenderId: '132264684965',
    projectId: 'flash-chat-c716f',
    storageBucket: 'flash-chat-c716f.appspot.com',
    iosClientId: '132264684965-9h7kcqmgar929nttg57m5jq7p31g578e.apps.googleusercontent.com',
    iosBundleId: 'com.flashchat.flashChat.RunnerTests',
  );
}
